### ISSUE TITLE
MR. PANDA 666

### ISSUE THREAD

**Issue by vladyio** [nandrienk/YandexM2017#4]
# MR. PANDA 666
:+1:  :+1:  :+1:  :+1: :+1:  :+1:  :+1:  :+1: :+1:  :+1:  :+1:  :+1: :+1:  :+1:  :+1:  :+1: :+1:  :+1:  :+1:  :+1: :+1:  :+1:  :+1:  :+1: :+1:  :+1:  :+1:  :+1: :+1:  :+1:  :+1:  :+1: :+1:  :+1:  :+1:  :+1: :+1:  :+1:  :+1:  :+1: :+1:  :+1:  :+1:  :+1: :+1:  :+1:  :+1:  :+1: :+1:  :+1:  :+1:  :+1: :+1:  :+1:  :+1:  :+1: :+1:  :+1:  :+1:  :+1: :+1:  :+1:  :+1:  :+1: :+1:  :+1:  :+1:  :+1: :+1:  :+1:  :+1:  :+1: :+1:  :+1:  :+1:  :+1: :+1:  :+1:  :+1:  :+1:

**Comment by nandrienk** [comment]
Hello Mr.Panda)

**Comment by vladyio** [comment]
close
